package prompts

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"watchtower/internal/db"
)

// TextGenerator generates text responses from a prompt. The caller only needs
// the text result, not usage metrics, so this is simpler than digest.Generator.
type TextGenerator interface {
	GenerateText(ctx context.Context, prompt string) (string, error)
}

// generatorAdapter wraps digest.Generator (passed as an interface{}) to avoid import cycles.
// The caller is responsible for providing a compatible Generate function.
type generatorAdapter struct {
	fn func(ctx context.Context, systemPrompt, userMessage string) (string, error)
}

func (g *generatorAdapter) GenerateText(ctx context.Context, prompt string) (string, error) {
	return g.fn(ctx, "", prompt)
}

// GenerateFunc creates a TextGenerator from a function that matches digest.Generator.Generate
// but discards the usage return value.
func GenerateFunc(fn func(ctx context.Context, systemPrompt, userMessage string) (string, error)) TextGenerator {
	return &generatorAdapter{fn: fn}
}

// TuneResult holds the AI's suggestion for an improved prompt.
type TuneResult struct {
	PromptID       string
	CurrentVersion int
	Suggestion     string   // the improved prompt text
	Explanation    string   // why these changes were made
	Changes        []string // bullet points of what changed
}

// Tuner generates prompt improvement suggestions based on user feedback.
type Tuner struct {
	store     *Store
	database  *db.DB
	generator TextGenerator
}

// NewTuner creates a tuner that uses the given generator for AI calls.
func NewTuner(store *Store, database *db.DB, gen TextGenerator) *Tuner {
	return &Tuner{store: store, database: database, generator: gen}
}

const tuneMetaPrompt = `You are a prompt engineering expert. Your task is to improve an AI prompt template based on user feedback.

Current prompt template (version %d):
---
%s
---

User feedback on outputs generated by this prompt:

GOOD examples (user liked these results):
%s

BAD examples (user did NOT like these results):
%s

Feedback statistics: %d positive, %d negative ratings.

Analyze the patterns in good vs bad outputs and suggest an improved prompt that:
1. Better captures what the user considers valuable (based on good examples)
2. Avoids generating content the user marks as bad
3. Preserves the output JSON format exactly (same fields, same structure)
4. Keeps all format placeholders (%%s, %%[1]s, etc.) in their original positions

Return ONLY a JSON object (no markdown fences):
{
  "improved_prompt": "the full improved prompt text with all placeholders preserved",
  "explanation": "2-3 sentences explaining what was changed and why",
  "changes": ["bullet point 1", "bullet point 2"]
}`

// Suggest generates an improvement suggestion for a prompt based on feedback.
func (t *Tuner) Suggest(ctx context.Context, promptID string) (*TuneResult, error) {
	// Load current prompt
	current, version, err := t.store.Get(promptID)
	if err != nil {
		return nil, fmt.Errorf("loading prompt %q: %w", promptID, err)
	}

	// Collect feedback examples
	feedback, err := t.database.GetFeedbackForPrompt(promptID, 50)
	if err != nil {
		return nil, fmt.Errorf("loading feedback: %w", err)
	}

	if len(feedback) == 0 {
		return nil, fmt.Errorf("no feedback found for prompt %q — need at least some ratings before tuning", promptID)
	}

	var goodExamples, badExamples []string
	var positive, negative int
	for _, fb := range feedback {
		// H4 fix: sanitize feedback comments to prevent prompt delimiter injection
		comment := strings.ReplaceAll(fb.Comment, "---", "- - -")
		comment = strings.ReplaceAll(comment, "===", "= = =")
		label := fmt.Sprintf("[%s #%s] %s", fb.EntityType, fb.EntityID, comment)
		if fb.Rating > 0 {
			goodExamples = append(goodExamples, label)
			positive++
		} else {
			badExamples = append(badExamples, label)
			negative++
		}
	}

	goodText := "(none)"
	if len(goodExamples) > 0 {
		goodText = strings.Join(goodExamples, "\n")
	}
	badText := "(none)"
	if len(badExamples) > 0 {
		badText = strings.Join(badExamples, "\n")
	}

	// Escape percent signs in the current template AND in feedback text (M3 fix)
	escaped := strings.ReplaceAll(current, "%", "%%")
	goodText = strings.ReplaceAll(goodText, "%", "%%")
	badText = strings.ReplaceAll(badText, "%", "%%")

	prompt := fmt.Sprintf(tuneMetaPrompt, version, escaped, goodText, badText, positive, negative)

	raw, err := t.generator.GenerateText(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("AI generation failed: %w", err)
	}

	// Parse the response
	var result struct {
		ImprovedPrompt string   `json:"improved_prompt"`
		Explanation    string   `json:"explanation"`
		Changes        []string `json:"changes"`
	}

	// M5 fix: try to extract JSON more robustly — find matching braces
	cleaned := strings.TrimSpace(raw)
	var parseErr error
	parsed := false
	for i := 0; i < len(cleaned); i++ {
		if cleaned[i] == '{' {
			candidate := cleaned[i:]
			if err := json.Unmarshal([]byte(candidate), &result); err == nil {
				parsed = true
				break
			}
			// Try from this { to last }
			if last := strings.LastIndex(candidate, "}"); last >= 0 {
				if err := json.Unmarshal([]byte(candidate[:last+1]), &result); err == nil {
					parsed = true
					break
				}
				parseErr = err
			}
		}
	}

	if !parsed {
		if parseErr != nil {
			return nil, fmt.Errorf("parsing tune result: %w", parseErr)
		}
		return nil, fmt.Errorf("parsing tune result: no JSON object found in response")
	}

	if result.ImprovedPrompt == "" {
		return nil, fmt.Errorf("AI returned empty improved prompt")
	}

	return &TuneResult{
		PromptID:       promptID,
		CurrentVersion: version,
		Suggestion:     result.ImprovedPrompt,
		Explanation:    result.Explanation,
		Changes:        result.Changes,
	}, nil
}

const tuneImportanceMetaPrompt = `You are a prompt engineering expert. Your task is to improve the IMPORTANCE classification criteria in an AI prompt template.

Current prompt template (version %d):
---
%s
---

The user has corrected the importance level on %d decisions. Here are the corrections:

%s

Analyze the pattern of corrections and improve the importance classification criteria in the prompt so the AI assigns importance levels that better match user expectations.

Rules:
1. Only modify the importance-related instructions (the section about high/medium/low classification)
2. Preserve the output JSON format exactly (same fields, same structure)
3. Keep all format placeholders (%%s, %%[1]s, etc.) in their original positions
4. Do NOT change other aspects of the prompt (topics, action items, summary, etc.)

Return ONLY a JSON object (no markdown fences):
{
  "improved_prompt": "the full improved prompt text with all placeholders preserved",
  "explanation": "2-3 sentences explaining what was changed in importance criteria",
  "changes": ["bullet point 1", "bullet point 2"]
}`

// SuggestImportance generates a prompt improvement based on importance corrections.
func (t *Tuner) SuggestImportance(ctx context.Context) (*TuneResult, error) {
	corrections, err := t.database.GetImportanceCorrections()
	if err != nil {
		return nil, fmt.Errorf("loading importance corrections: %w", err)
	}
	if len(corrections) == 0 {
		return nil, fmt.Errorf("no importance corrections found — change importance on some decisions first")
	}

	// Use digest.channel prompt since that's where importance is generated
	promptID := DigestChannel
	current, version, err := t.store.Get(promptID)
	if err != nil {
		return nil, fmt.Errorf("loading prompt %q: %w", promptID, err)
	}

	// Format corrections for the meta-prompt
	var lines []string
	for _, c := range corrections {
		text := strings.ReplaceAll(c.DecisionText, "---", "- - -")
		text = strings.ReplaceAll(text, "===", "= = =")
		lines = append(lines, fmt.Sprintf("- Decision: %q\n  AI said: %s → User corrected to: %s",
			text, c.OriginalImportance, c.NewImportance))
	}
	correctionsText := strings.Join(lines, "\n")
	correctionsText = strings.ReplaceAll(correctionsText, "%", "%%")

	escaped := strings.ReplaceAll(current, "%", "%%")
	prompt := fmt.Sprintf(tuneImportanceMetaPrompt, version, escaped, len(corrections), correctionsText)

	raw, err := t.generator.GenerateText(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("AI generation failed: %w", err)
	}

	var result struct {
		ImprovedPrompt string   `json:"improved_prompt"`
		Explanation    string   `json:"explanation"`
		Changes        []string `json:"changes"`
	}

	cleaned := strings.TrimSpace(raw)
	var parseErr error
	parsed := false
	for i := 0; i < len(cleaned); i++ {
		if cleaned[i] == '{' {
			candidate := cleaned[i:]
			if err := json.Unmarshal([]byte(candidate), &result); err == nil {
				parsed = true
				break
			}
			if last := strings.LastIndex(candidate, "}"); last >= 0 {
				if err := json.Unmarshal([]byte(candidate[:last+1]), &result); err == nil {
					parsed = true
					break
				}
				parseErr = err
			}
		}
	}

	if !parsed {
		if parseErr != nil {
			return nil, fmt.Errorf("parsing tune result: %w", parseErr)
		}
		return nil, fmt.Errorf("parsing tune result: no JSON object found in response")
	}

	if result.ImprovedPrompt == "" {
		return nil, fmt.Errorf("AI returned empty improved prompt")
	}

	return &TuneResult{
		PromptID:       promptID,
		CurrentVersion: version,
		Suggestion:     result.ImprovedPrompt,
		Explanation:    result.Explanation,
		Changes:        result.Changes,
	}, nil
}

// ApplyImportance applies the importance tuning result and clears corrections.
func (t *Tuner) ApplyImportance(result *TuneResult) error {
	if err := t.Apply(result); err != nil {
		return err
	}
	return t.database.ClearImportanceCorrections()
}

// HasImportanceCorrections returns true if there are pending corrections.
func (t *Tuner) HasImportanceCorrections() bool {
	exists, err := t.database.HasImportanceCorrections()
	if err != nil {
		return false
	}
	return exists
}

// Apply saves the tuning suggestion as a new prompt version.
// Returns an error if the prompt has been modified since the suggestion was generated.
func (t *Tuner) Apply(result *TuneResult) error {
	// Check that the prompt hasn't been changed since the suggestion was generated.
	_, currentVersion, err := t.store.Get(result.PromptID)
	if err != nil {
		return fmt.Errorf("checking current version: %w", err)
	}
	if currentVersion != result.CurrentVersion {
		return fmt.Errorf("prompt %q was modified (v%d → v%d) since the suggestion was generated; re-run tune to get a fresh suggestion",
			result.PromptID, result.CurrentVersion, currentVersion)
	}

	reason := fmt.Sprintf("auto-tune from v%d: %s", result.CurrentVersion, result.Explanation)
	// M6 fix: rune-safe truncation to avoid splitting multi-byte UTF-8 characters
	if runes := []rune(reason); len(runes) > 200 {
		reason = string(runes[:200])
	}
	return t.store.Update(result.PromptID, result.Suggestion, reason)
}
