import Foundation

/// Structured running summary generated by AI as part of channel digest.
/// Stored as JSON in the `running_summary` column of `digests`.
struct RunningSummary: Codable, Equatable {
    let activeTopics: [ActiveTopic]?
    let recentDecisions: [RecentDecision]?
    let channelDynamics: String?
    let openQuestions: [String]?
    let meta: Meta?

    enum CodingKeys: String, CodingKey {
        case activeTopics = "active_topics"
        case recentDecisions = "recent_decisions"
        case channelDynamics = "channel_dynamics"
        case openQuestions = "open_questions"
        case meta
    }

    struct Meta: Codable, Equatable {
        let generatedAt: String?
        let digestID: String?
        let messageCount: Int?
        let period: String?

        enum CodingKeys: String, CodingKey {
            case generatedAt = "generated_at"
            case digestID = "digest_id"
            case messageCount = "message_count"
            case period
        }
    }
}

struct ActiveTopic: Codable, Equatable, Identifiable {
    var id: String { topic }

    let topic: String
    let status: String?
    let started: String?
    let lastUpdate: String?
    let keyParticipants: [String]?
    let summary: String?

    enum CodingKeys: String, CodingKey {
        case topic, status, started, summary
        case lastUpdate = "last_update"
        case keyParticipants = "key_participants"
    }
}

struct RecentDecision: Codable, Equatable, Identifiable {
    var id: String { decision + (date ?? "") }

    let decision: String
    let date: String?
    let by: String?
    let status: String?
}
